.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH carbonado-key-path 1  "carbonado-key-path " 
.SH NAME
carbonado\-key\-path \- Print the path where the mnemonic is stored
.SH SYNOPSIS
\fBcarbonado\-key\-path\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print the path where the mnemonic is stored
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
