.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH carbonado-key-show 1  "carbonado-key-show " 
.SH NAME
carbonado\-key\-show \- Print the persisted mnemonic (sensitive — writes to stdout)
.SH SYNOPSIS
\fBcarbonado\-key\-show\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Print the persisted mnemonic (sensitive — writes to stdout)
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
